server:
  port: 8080
  context-path: /spring-boot
  
spring:
  thymeleaf:
    cache: false
    mode: HTML

  datasource:
    name: spring-boot
    #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_spring?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tangzhihe.domain

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    